INSERT OR IGNORE INTO `dismissed_keywords` (`portal`, `normalized_keyword`)
SELECT 'all', `normalized_keyword`
FROM `keywords`
WHERE `keyword` LIKE '%사망%'
   OR `keyword` LIKE '%숨진%'
   OR `keyword` LIKE '%숨져%'
   OR `keyword` LIKE '%별세%'
   OR `keyword` LIKE '%살인%'
   OR `keyword` LIKE '%살해%'
   OR `keyword` LIKE '%피살%'
   OR `keyword` LIKE '%시신%'
   OR `keyword` LIKE '%극단적 선택%'
   OR `keyword` LIKE '%19금%'
   OR `keyword` LIKE '%야동%'
   OR `keyword` LIKE '%음란%'
   OR `keyword` LIKE '%포르노%'
   OR `keyword` LIKE '%성관계%'
   OR `keyword` LIKE '%성폭력%'
   OR `keyword` LIKE '%성추행%'
   OR `keyword` LIKE '%강간%'
   OR `keyword` = '성인'
   OR `keyword` LIKE '% 성인%'
   OR `keyword` LIKE '%성인 %'
   OR `keyword` LIKE '%이혼%'
   OR `keyword` LIKE '%파경%'
   OR `keyword` LIKE '%혐오%'
   OR `keyword` LIKE '%극혐%'
   OR (`keyword` LIKE '%비하%' AND `keyword` NOT LIKE '%비하인드%')
   OR (`keyword` LIKE '%차별%' AND `keyword` NOT LIKE '%차별화%')
   OR `keyword` LIKE '%로또%'
   OR `keyword` LIKE '%복권%'
   OR `keyword` LIKE '%당첨번호%'
   OR `keyword` LIKE '%당첨 번호%'
   OR `keyword` LIKE '%행운번호%'
   OR `keyword` LIKE '%행운 번호%'
   OR `keyword` LIKE '%퀴즈%'
   OR `keyword` LIKE '%정답%'
   OR `keyword` LIKE '%캐시워크%'
   OR `keyword` LIKE '%오퀴즈%'
   OR LOWER(`keyword`) LIKE '% ssg %'
   OR LOWER(`keyword`) LIKE 'ssg %'
   OR LOWER(`keyword`) LIKE '% kia %'
   OR LOWER(`keyword`) LIKE 'kia %'
   OR LOWER(`keyword`) LIKE '% kbo%'
   OR LOWER(`keyword`) LIKE '% mlb%'
   OR LOWER(`keyword`) LIKE '% epl%'
   OR LOWER(`keyword`) LIKE '% nba%'
   OR LOWER(`keyword`) LIKE '% nfl%'
   OR LOWER(`keyword`) LIKE '% nhl%'
   OR LOWER(`keyword`) LIKE '% ufc%'
   OR LOWER(`keyword`) LIKE '% fifa%'
   OR LOWER(`keyword`) LIKE '% afc%'
   OR LOWER(`keyword`) LIKE '% fc%'
   OR `keyword` LIKE '%야구%'
   OR `keyword` LIKE '%축구%'
   OR `keyword` LIKE '%농구%'
   OR (`keyword` LIKE '%배구%' AND `keyword` NOT LIKE '%배구조%')
   OR `keyword` LIKE '%골프%'
   OR `keyword` LIKE '%테니스%'
   OR `keyword` LIKE '%배드민턴%'
   OR `keyword` LIKE '%탁구%'
   OR (`keyword` LIKE '%수영%' AND `keyword` NOT LIKE '%수영복%')
   OR `keyword` LIKE '%육상%'
   OR `keyword` LIKE '%복싱%'
   OR `keyword` LIKE '%격투기%'
   OR `keyword` LIKE '%올림픽%'
   OR `keyword` LIKE '%월드컵%'
   OR `keyword` LIKE '%아시안게임%'
   OR `keyword` LIKE '%선수%'
   OR `keyword` LIKE '%투수%'
   OR `keyword` LIKE '%타자%'
   OR `keyword` LIKE '%포수%'
   OR `keyword` LIKE '%외야수%'
   OR `keyword` LIKE '%내야수%'
   OR `keyword` LIKE '%구단%'
   OR `keyword` LIKE '%트레이드%'
   OR `keyword` LIKE '%홈런%'
   OR `keyword` LIKE '%이닝%'
   OR `keyword` LIKE '%무실점%'
   OR `keyword` LIKE '%원정 경기%'
   OR `keyword` LIKE '%선발 등판%'
   OR `keyword` LIKE '%완봉%'
   OR `keyword` LIKE '%승점%'
   OR `keyword` LIKE '%챔피언스리그%'
   OR `keyword` LIKE '%프리미어리그%'
   OR `keyword` LIKE '%첼시%'
   OR `keyword` LIKE '%아스널%'
   OR `keyword` LIKE '%리버풀%'
   OR `keyword` LIKE '%맨유%'
   OR `keyword` LIKE '%맨시티%'
   OR `keyword` LIKE '%토트넘%'
   OR `keyword` LIKE '%바르셀로나%'
   OR `keyword` LIKE '%레알마드리드%'
   OR `keyword` LIKE '%바이에른%';--> statement-breakpoint

DELETE FROM `keywords`
WHERE `normalized_keyword` IN (
  SELECT `normalized_keyword`
  FROM `dismissed_keywords`
  WHERE `portal` = 'all'
);
