INSERT OR IGNORE INTO `dismissed_keywords` (`portal`, `normalized_keyword`)
SELECT 'all', `normalized_keyword`
FROM `keywords`
WHERE LOWER(`keyword`) LIKE 'nc %'
   OR LOWER(`keyword`) LIKE '% nc %'
   OR LOWER(`keyword`) LIKE 'klpga %'
   OR LOWER(`keyword`) LIKE '% klpga %'
   OR LOWER(`keyword`) LIKE 'kpga %'
   OR LOWER(`keyword`) LIKE '% kpga %'
   OR LOWER(`keyword`) LIKE 'kbl %'
   OR LOWER(`keyword`) LIKE '% kbl %'
   OR LOWER(`keyword`) LIKE 'wkbl %'
   OR LOWER(`keyword`) LIKE '% wkbl %'
   OR LOWER(`keyword`) LIKE 'kovo %'
   OR LOWER(`keyword`) LIKE '% kovo %'
   OR LOWER(`keyword`) LIKE 'lafc %'
   OR LOWER(`keyword`) LIKE '% lafc %'
   OR LOWER(`keyword`) LIKE 'pba %'
   OR LOWER(`keyword`) LIKE '% pba %'
   OR LOWER(`keyword`) LIKE 'lpba %'
   OR LOWER(`keyword`) LIKE '% lpba %'
   OR LOWER(`keyword`) LIKE 'lpga %'
   OR LOWER(`keyword`) LIKE '% lpga %'
   OR LOWER(`keyword`) LIKE 'pga %'
   OR LOWER(`keyword`) LIKE '% pga %'
   OR LOWER(`keyword`) LIKE '% mvp%'
   OR `keyword` LIKE '%야수%'
   OR `keyword` LIKE '%안타%'
   OR `keyword` LIKE '%타구%'
   OR `keyword` LIKE '%타율%'
   OR `keyword` LIKE '%방어율%'
   OR `keyword` LIKE '%볼넷%'
   OR `keyword` LIKE '%삼진%'
   OR `keyword` LIKE '%도루%'
   OR `keyword` LIKE '%타점%'
   OR `keyword` LIKE '%세이브%'
   OR `keyword` LIKE '%홀드%'
   OR `keyword` LIKE '%투구%'
   OR `keyword` LIKE '%등판%'
   OR `keyword` LIKE '%마운드%'
   OR `keyword` LIKE '%득점%'
   OR `keyword` LIKE '%실점%'
   OR `keyword` LIKE '%완투%'
   OR `keyword` LIKE '%승부차기%';--> statement-breakpoint

INSERT OR IGNORE INTO `dismissed_keywords` (`portal`, `normalized_keyword`)
SELECT 'all', `normalized_keyword`
FROM `keywords`
WHERE `keyword` LIKE '%리그스컵%'
   OR `keyword` LIKE '%메이저리그%'
   OR `keyword` LIKE '%메이저 리그%'
   OR `keyword` LIKE '%K리그%'
   OR `keyword` LIKE '%k리그%'
   OR `keyword` LIKE '%퓨처스리그%'
   OR `keyword` LIKE '%시구%'
   OR `keyword` LIKE '%시타%'
   OR `keyword` LIKE '%결승타%'
   OR `keyword` LIKE '%연승%'
   OR `keyword` LIKE '%연패%'
   OR `keyword` LIKE '%무승부%'
   OR `keyword` LIKE '%국가대표%'
   OR `keyword` LIKE '%대표팀%'
   OR `keyword` LIKE '%드래프트%'
   OR `keyword` LIKE '%교체 출전%'
   OR `keyword` LIKE '%연속골%'
   OR `keyword` LIKE '%사격%'
   OR `keyword` LIKE '%양궁%'
   OR `keyword` LIKE '%역도%'
   OR `keyword` LIKE '%승마%'
   OR `keyword` LIKE '%빙상%'
   OR `keyword` LIKE '%스케이팅%'
   OR `keyword` LIKE '%스노보드%'
   OR `keyword` LIKE '%컬링%'
   OR `keyword` LIKE '%바둑%'
   OR `keyword` LIKE '%체스%'
   OR `keyword` LIKE '%리그오브레전드%'
   OR `keyword` LIKE '%오로라월드%'
   OR `keyword` LIKE '%원정경기%'
   OR `keyword` LIKE '%홈경기%'
   OR `keyword` LIKE '%경기 결과%'
   OR `keyword` LIKE '%경기 일정%'
   OR `keyword` LIKE '%경기 중계%'
   OR `keyword` LIKE '%경기 출전%'
   OR `keyword` LIKE '%경기 결장%'
   OR `keyword` LIKE '%KT전%'
   OR `keyword` LIKE '%LG전%'
   OR `keyword` LIKE '%NC전%'
   OR `keyword` LIKE '%KIA전%'
   OR `keyword` LIKE '%SSG전%'
   OR `keyword` GLOB '*[0-9]승*'
   OR `keyword` GLOB '*[0-9]패*'
   OR `keyword` GLOB '*[0-9]경기*';--> statement-breakpoint

INSERT OR IGNORE INTO `dismissed_keywords` (`portal`, `normalized_keyword`)
SELECT 'all', `normalized_keyword`
FROM `keywords`
WHERE `keyword` LIKE '%임지민%'
   OR `keyword` LIKE '%이정후%'
   OR `keyword` LIKE '%최혜진%'
   OR `keyword` LIKE '%고영표%'
   OR `keyword` LIKE '%이숭용%'
   OR `keyword` LIKE '%하영민%'
   OR `keyword` LIKE '%류중일%'
   OR `keyword` LIKE '%김민솔%'
   OR `keyword` LIKE '%최민석%'
   OR `keyword` LIKE '%손흥민%'
   OR `keyword` LIKE '%백인천%'
   OR `keyword` LIKE '%추신수%'
   OR `keyword` LIKE '%배지환%'
   OR `keyword` LIKE '%힐리어드%'
   OR `keyword` LIKE '%장은수%'
   OR `keyword` LIKE '%이강인%'
   OR `keyword` LIKE '%강채연%'
   OR `keyword` LIKE '%염경엽%'
   OR `keyword` LIKE '%시메오네%'
   OR `keyword` LIKE '%배준호%'
   OR `keyword` LIKE '%마레스카%'
   OR `keyword` LIKE '%김원형%'
   OR `keyword` LIKE '%송교창%'
   OR `keyword` LIKE '%설종진%'
   OR `keyword` LIKE '%지단%'
   OR (`keyword` LIKE '%사비%' AND `keyword` LIKE '%감독%')
   OR `keyword` LIKE '%만치니%';--> statement-breakpoint

DELETE FROM `keywords`
WHERE `normalized_keyword` IN (
  SELECT `normalized_keyword`
  FROM `dismissed_keywords`
  WHERE `portal` = 'all'
);
